Added Jellyfin Segment Editor
awesome-jellyfin/awesome-jellyfin pull request #42
Opened 2023-12-26 21:04 UTC by Bugreporter48

It manage Jellyfin Media Segment positions.

Project link: https://github.com/endrl/segment-editor

2023-12-30 19:29 UTC, TomRomeo requested changes
Please correct the position of this item in the list so it stays ordered alphabetically

2024-01-05 13:22 UTC, Bugreporter48 reviewed
done

2024-01-05 13:22 UTC, darmiel approved these changes

2024-01-08 09:39 UTC, TomRomeo approved these changes

2024-01-08 09:40 UTC, merged